
### Ping

GET http://localhost:8000/ping


### Write message

POST http://localhost:8000/kafka

{
    "org_id": "92934",
    "request_id": "9823ndai732",
    "b64_identity": "eyJpZGVudGl0eSI6eyJ0eXBlIjoidXNlciwiYWNjb3VudF9udW1iZXIiOiI5NDc5MjMifX0=",
    "state": "Pending",
    "url": "myprotocol:#//www.google.com",
    "status": "Valid",
    "anyfield": "anyvalue"
}

### Read all the messages

GET http://localhost:8000/kafka
