kafka:
  auto:
    offset:
      reset: latest
    commit:
      interval:
        ms: 5000
  bootstrap:
    servers: localhost:9092
  group:
    id: content-sources
  message:
    send:
      max:
        retries: 15
  request:
    timeout:
      ms: 30000
    required:
      acks: -1
  retry:
    backoff:
      ms: 100
  timeout: 10000
  topics:
    - repos-introspect
  # sasl:
  #   username: someusername
  #   passowrd: somepassword
  #   mechanism: somemechanism
  #   protocol: someprotocol
database:
  host: localhost
  port: 5432
  user: content
  password: content
  name: content
logging:
  level: debug
  console: True
seed:
  repository_configurations:
    org_id: "13441076"
    size: 2
  repository_rpms:
    size: 10
  repositories:
    size: 3
certs:
  cert_path: "/home/avisiedo/hmscontent/content-sources-backend/configs/secrets/cdncert/cert.pem"
options:
  paged_rpm_inserts_limit: 200
